version: '2'

services: 
    peer-base:
        image: hyperledger/fabric-peer:latest
        environment: 
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_bookshare
            - FABRIC_LOGGING_SPEC=info
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_PEER_MSPCONFIGPATH=/peer/msp
        volumes: 
            - /var/run/:/host/var/run
        command: peer node start
    orderer-base:
        image: hyperledger/fabric-orderer:latest
        environment: 
            - FABRIC_LOGGING_SPEC=INFO
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/channel-artifacts/genesis.block
            - ORDERER_GENERAL_LOCALMSPDIR=/orderer/msp
            - ORDERER_GENERAL_TLS_ENABLED=false
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/orderer/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/orderer/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/orderer/tls/ca.crt]
            - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/orderer/tls/server.crt
            - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/orderer/tls/server.key
            - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/orderer/tls/ca.crt] 
        command: orderer
    ca-base:
        image: hyperledger/fabric-ca:latest
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_TLS_ENABLED=false
            - FABRIC_CA_SERVER_TLS_CERTFILE=/ca/cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/ca/PRIVATE_KEY
            - FABRIC_CA_SERVER_PORT=7054
        command: sh -c 'fabric-ca-server start --ca.certfile /ca/cert.pem --ca.keyfile /ca/PRIVATE_KEY -b admin:adminpw'