version: '2'
volumes:
    data-host:
    data-orderer:
    data-ca:
    data-database:
networks:
    bookshare:
services:
    hostpeer:
        container_name: devpeer
        extends:
            file: base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=devpeer
            - CORE_PEER_ADDRESS:devpeer:7051
            - CORE_PEER_LOCALMSPID=HostMSP
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=database:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
        volumes:
            - ../crypto-config/peerOrganizations/host.com/peers/devpeer:/peer
            - data-host:/var/hyperledger/production
        depends_on:
            - database
        networks:
            - bookshare
        ports:
            - 7051:7051
    database:
        container_name: database
        image: hyperledger/fabric-couchdb:latest
        environment:
            - COUCHDB_USER=
            - COUCHDB_PASSWORD=
        volumes:
            - data-database:/opt/couchdb
        networks:
            - bookshare
        ports:
            - 5984:5984
    orderer:
        extends:
            file: base.yaml
            service: orderer-base
        container_name: orderer
        networks:
            - bookshare
        environment:
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
        volumes:
            - data-orderer:/var/hyperledger/production/orderer
            - ../channel-artifacts:/channel-artifacts
            - ../crypto-config/ordererOrganizations/orderer.com/orderers/orderer:/orderer
        ports:
            - 7050:7050
    ca:
        container_name: ca
        extends:
            file: base.yaml
            service: ca-base
        environment:
            - FABRIC_CA_SERVER_CA_NAME=ca
        volumes:
            - ../crypto-config/peerOrganizations/host.com/ca:/ca
            - data-ca:/etc/hyperledger/fabric-ca-server
        ports:
            - 7054:7054
        networks:
            - bookshare
    cli:
        container_name: cli
        image: hyperledger/fabric-tools:latest
        tty: true
        stdin_open: true
        environment:
            - GOPATH=/opt/gopath
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_ID=cli
            - CORE_PEER_ADDRESS=devpeer:7051
            - CORE_PEER_LOCALMSPID=HostMSP
            - CORE_PEER_MSPCONFIGPATH=/crypto-config/peerOrganizations/host.com/users/Admin@host.com/msp
            - CORE_PEER_TLS_ENABLED=false
            - CORE_PEER_TLS_CERT_FILE=/crypto-config/peerOrganizations/host.com/users/Admin@host.com/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/crypto-config/peerOrganizations/host.com/users/Admin@host.com/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/crypto-config/peerOrganizations/host.com/users/Admin@host.com/tls/ca.crt
        volumes:
            - ../crypto-config:/crypto-config
            - ../channel-artifacts:/channel-artifacts
            - /var/run/:/host/var/run/
            - ../../chaincode:/opt/gopath/src/chaincode
        networks:
            - bookshare
